### ISSUE TITLE
Username validation required on signup form

### ISSUE THREAD

**Issue by saadjs** [appacademy-starters/python-project-starter#6]
Currently, the Signup form is only checking if email already exists in the database.
If a new email entered with an already existing username, the signup route throws 500 internal server error.

```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "users_username_key"
DETAIL:  Key (username)=(saad) already exists.
```

**Comment by jshafto** [comment]
Thanks for flagging this—I looked into it, and because this is a project, this is designed so that students can implement their own validator for this if they choose.
